version: '2'

services:
    turtle_controller:
        build:
            context: ../
            dockerfile: eg2/Dockerfile
        command: ros2 launch my_turtle_bringup only_controller.launch.py
    turtle_sim:
        image: osrf/ros:humble-desktop
        # runtime: nvidia
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=/tmp/.docker.xauth
            # - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /tmp/.docker.xauth:/tmp/.docker.xauth
        command: ros2 run turtlesim turtlesim_node
        depends_on:
            - turtle_controller
